let dades = [
    {
        "name":"SMART LIGHTING",
        "info":"As the motorbike moves, its position on the ground shifts, so the New Lighting System of the Diablo X shifts will move when riding it on corners, to provide the best lighting & vision of the road ahead.",
        "video":'<iframe id="youtube-video2" frameborder="0" allow="autoplay;" src="https://www.youtube.com/embed/y5o-a5TInE0?loop=1;enablejsapi=1&amp;disablekb=1&amp;controls=0&amp;rel=0&amp;iv_load_policy=3&amp;cc_load_policy=0&amp;playsinline=1&amp;showinfo=0&amp;modestbranding=1&amp;fs=0&amp;origin=https://puig.tv&amp;mute=1&amp;autoplay=1&amp;loop=1&amp;playlist=y5o-a5TInE0"  style="opacity: 1;" title="DiabloX"></iframe>',
    },

    {
        "name":"ELECTRONIC SCREEN & DEFLECTORS",
        "info":"The new screen, aerodynamically optimized and bigger, moves up and down electronically to give an adjustable aerodynamic protection of 150mm depending on the needs of each moment and rider. The mechanism is a continuous path and it moves pushing a button and can be stopped wherever we desire for an adaptable protection.",
        "video":'<iframe id="youtube-video2" frameborder="0" allow="autoplay;" src="https://www.youtube.com/embed/CBrEjuuqkTo?loop=1;enablejsapi=1&amp;disablekb=1&amp;controls=0&amp;rel=0&amp;iv_load_policy=3&amp;cc_load_policy=0&amp;playsinline=1&amp;showinfo=0&amp;modestbranding=1&amp;fs=0&amp;origin=https://puig.tv&amp;mute=1&amp;autoplay=1&amp;loop=1&amp;playlist=CBrEjuuqkTo"  style="opacity: 1;" title="DiabloX"></iframe>',
    },

    {
        "name":"REAR SEAT COWL",
        "info":"The fins in the rear seat cowl clean the airflow to reduce resistance and above all stabilize the bike when braking. Also, on the upper part we manage to provide vertical load, achieving a more stable and balanced bike and better braking.",
        "video":'<iframe id="youtube-video2" frameborder="0" allow="autoplay;" src="https://www.youtube.com/embed/RPc6AM60K3U?loop=1;enablejsapi=1&amp;disablekb=1&amp;controls=0&amp;rel=0&amp;iv_load_policy=3&amp;cc_load_policy=0&amp;playsinline=1&amp;showinfo=0&amp;modestbranding=1&amp;fs=0&amp;origin=https://puig.tv&amp;mute=1&amp;autoplay=1&amp;loop=1&amp;playlist=RPc6AM60K3U"  style="opacity: 1;" title="DiabloX"></iframe>',
    },

    {
        "name":"BRAKE COOLING SYSTEM",
        "info":"With the aim of reducing the turbulence generated by the front wheel and achieving the perfect working temperature for braking, we designed this brake cooling system that, by channeling the air directly to the disks and calipers, cools them and prevents the braking system from malfunctioning due to overheating. And also reduces front wheel vibrations produced by air turbulences.",
        "video":'<iframe id="youtube-video2" frameborder="0" allow="autoplay;" src="https://www.youtube.com/embed/SnOTSzCZEFM?loop=1;enablejsapi=1&amp;disablekb=1&amp;controls=0&amp;rel=0&amp;iv_load_policy=3&amp;cc_load_policy=0&amp;playsinline=1&amp;showinfo=0&amp;modestbranding=1&amp;fs=0&amp;origin=https://puig.tv&amp;mute=1&amp;autoplay=1&amp;loop=1&amp;playlist=SnOTSzCZEFM"  style="opacity: 1;" title="DiabloX"></iframe>',
    },

    {
        "name":"SMART WINGLETS",
        "info":"The DiabloX incorporate 4 smart winglets with servo motors and a sensor that tilt them to the optimal angle when it detects strong accelerations or when the rider activates it. The shape of the spoiler has been redesigned searching the optimal airfoil to take advantage of them in any situation, creating the maximum downforce without compromising drag force. Together with the cover that surrounds them form an air channel that accelerates and compacts the air to achieve the maximum effect.",
        "video":'<iframe id="youtube-video2" frameborder="0" allow="autoplay;" src="https://www.youtube.com/embed/hhI82TTFD44?loop=1;enablejsapi=1&amp;disablekb=1&amp;controls=0&amp;rel=0&amp;iv_load_policy=3&amp;cc_load_policy=0&amp;playsinline=1&amp;showinfo=0&amp;modestbranding=1&amp;fs=0&amp;origin=https://puig.tv&amp;mute=1&amp;autoplay=1&amp;loop=1&amp;playlist=hhI82TTFD44"  style="opacity: 1;" title="DiabloX"></iframe>',
    },

    {
        "name":"LENTICULAR RIM",
        "info":"From an aerodynamic perspective, the rear tyre spinning creates a lot of turbulence that results as an added drag force that prevents the motorcycle from advancing. By covering this wheel we improve the drag force of the overall motorcycle, and reduce turbulence.",
        "video":'<iframe id="youtube-video2" frameborder="0" allow="autoplay;" src="https://www.youtube.com/embed/Lkq1WqJ_I3w?loop=1;enablejsapi=1&amp;disablekb=1&amp;controls=0&amp;rel=0&amp;iv_load_policy=3&amp;cc_load_policy=0&amp;playsinline=1&amp;showinfo=0&amp;modestbranding=1&amp;fs=0&amp;origin=https://puig.tv&amp;mute=1&amp;autoplay=1&amp;loop=1&amp;playlist=Lkq1WqJ_I3w"  style="opacity: 1;" title="DiabloX"></iframe>',
    },
];